#define CLOCK_SCC_SKS_FH				0
#define CLOCK_SCC_CKS_DIV2				1
#define CLOCK_SCC_SCK_DIV4				2
#define CLOCK_SCC_CKS_DIV8				3
#define CLOCK_SCC_CKS_DIV16				4
#define CLOCK_SCC_CKS_DIV32				5
#define CLOCK_SCC_CKS_DIV64				6
#define CLOCK_SCC_CKS_FSUB				7
#define CLOCK_SCC_CKS_STATUS			7

#define CLOCK_SCC_FHS_HIRC				0
#define CLOCK_SCC_FHS_HXT				1
#define CLOCK_SCC_FHS_STATUS			1

#define CLOCK_SCC_FSS_LIRC				0
#define CLOCK_SCC_FSS_LXT				1
#define CLOCK_SCC_FSS_STATUS			1

#define CLOCK_SCC_FHIDEN_DISABLE		0
#define CLOCK_SCC_FHIDEN_ENABLE			1
#define CLOCK_SCC_FHIDEN_STATUS			1

#define CLOCK_SCC_FSIDEN_DISABLE		0
#define CLOCK_SCC_FSIDEN_ENABLE			1
#define CLOCK_SCC_FSIDEN_STATUS			1

#define CLOCK_HIRCC_HIRC_8MHZ			0
#define CLOCK_HIRCC_HIRC_12MHZ			1
#define CLOCK_HIRCC_HIRC_16MHZ			2
#define CLOCK_HIRCC_HIRC_18MHZ			3
#define CLOCK_HIRCC_HIRC_STATUS			3

#define CLOCK_HIRCC_HIRCF_STABLE		0
#define CLOCK_HIRCC_HIRCF_UNSTABLE		1
#define CLOCK_HIRCC_HIRCF_STATUS		1

#define CLOCK_HIRCC_HIRCEN_DISABLE		0
#define CLOCK_HIRCC_HIRCEN_ENABLE		1
#define CLOCK_HIRCC_HIRCEN_STATUS		1

#define CLOCK_HXTC_HXTM_SUB10MHZ		0
#define CLOCK_HXTC_HXTM_MORE10MHZ		1
#define CLOCK_HXTC_HXTM_STATUS			1

#define CLOCK_HXTC_HXTF_DISABLE			0
#define CLOCK_HXTC_HXTF_SABLE			1
#define CLOCK_HXTC_HXTF_STATUS			1

#define CLOCK_HXTC_HXTEN_DISABLE		0
#define CLOCK_HXTC_HXTEN_ENABLE			1
#define CLOCK_HXTC_HXTEN_STATUS			1

#define CLOCK_LXTC_LXTF_DISABLE			0
#define CLOCK_LXTC_LXTF_ENABLE			1
#define CLOCK_LXTC_LXTF_STATUS			1

#define CLOCK_LXTC_LXTEN_DISABLE		0
#define CLOCK_LXTC_LXTEN_ENABLE			1
#define CLOCK_LXTC_LXTEN_STATUS			1	

void clockSetSystemSrc(uint8_t source ,uint8_t hz ,uint8_t div);